### ISSUE TITLE
Save full transformed data to SQL

### ISSUE THREAD

**Issue by MckinstryJ** [MckinstryJ/PocketOr#20]
- [ ] pull full data from csv (at first)
- [ ] transform data as n -> n+1 ROC
- [ ] save to SQLite file
