### ISSUE TITLE
Find specific models for all

### ISSUE THREAD

**Issue by MckinstryJ** [MckinstryJ/PocketOr#23]
- [ ] Conduct exhaustive search for each model
- [ ] Select top 2 models for model selection
- [ ] Remove rest in Model Selection
